In [11]:
import numpy as np

arr = np.arange(1, 21)

print(arr)
print("Shape of an array:", arr.shape)
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

matrix = arr.reshape(4, 5)

print(matrix)
print(matrix[1])
print(matrix[2])
print ("jahnavi")

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Shape of an array: (20,)
Maximum: 20
Minimum: 1
Mean: 10.5
Standard Deviation: 5.766281297335398
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 6  7  8  9 10]
[11 12 13 14 15]
jahnavi


In [16]:
import numpy as np

A = np.array([10, 20, 30, 40, 50])
B = np.array([5, 10, 15, 20, 25])

print("Addition of A and B:", A + B)
print("Subtraction of B from A:", A - B)
print("Element-wise Multiplication:", A * B)
print("Element-wise Division:", A / B)
print("Sum of all elements in A:", A.sum())
print ("jahnavi")

Addition of A and B: [15 30 45 60 75]
Subtraction of B from A: [ 5 10 15 20 25]
Element-wise Multiplication: [  50  200  450  800 1250]
Element-wise Division: [2. 2. 2. 2. 2.]
Sum of all elements in A: 150
jahnavi


In [3]:
!mamba install pandas

mambajs 0.21.1

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 4.0475 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.3    np23py313h1e705a5_0  emscripten-forge-4x
+ python-tzdata  2026.2   pyhd8ed1ab_0         conda-forge
- pip            26.1.2   pyh145f28c_0         conda-forge


In [15]:
import pandas as pd

data = {
    "roll no" : [101,102,103,104,105],
    "names": ["ravi","priya"," kiran" , "anu", "sita"],
    "marks":[85,92,78,88,95]
}

df=pd.DataFrame(data)
print(df)
print(df.columns.tolist())
print(" first three records\n" , df.head(3))

average = df["marks"].mean()
print("average:" , average)

highest =df.loc[df["marks"].idxmax()]
print("highest marks :" , highest)

lowest = df.loc[df["marks"].idxmin()]
print("lowest marks :", lowest)

def grade(marks):
    if marks >= 90 :
        return "A"
    elif marks >= 80:
        return "B"
    else:
        return "c"

df["grade"] = df["marks"].apply(grade)
print(df["grade"])
print ("jahnavi")

   roll no   names  marks
0      101    ravi     85
1      102   priya     92
2      103   kiran     78
3      104     anu     88
4      105    sita     95
['roll no', 'names', 'marks']
 first three records
    roll no   names  marks
0      101    ravi     85
1      102   priya     92
2      103   kiran     78
average: 87.6
highest marks : roll no     105
names      sita
marks        95
Name: 4, dtype: object
lowest marks : roll no       103
names       kiran
marks          78
Name: 2, dtype: object
0    B
1    A
2    c
3    B
4    A
Name: grade, dtype: str
jahnavi


In [14]:
import pandas as pd
data = {
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "Price": [50000, 500, 1200, 10000],
    "Quantity": [10, 50, 30, 15]
}
df = pd.DataFrame(data)
df["Total Value"] = df["Price"] * df["Quantity"]
print("DataFrame:")
print(df)

print("\nProduct with Highest Total Value:")
print(df[df["Total Value"] == df["Total Value"].max()])

print("\nOverall Inventory Value:")
print(df["Total Value"].sum())

print ("jahnavi")

DataFrame:
    Product  Price  Quantity  Total Value
0    Laptop  50000        10       500000
1     Mouse    500        50        25000
2  Keyboard   1200        30        36000
3   Monitor  10000        15       150000

Product with Highest Total Value:
  Product  Price  Quantity  Total Value
0  Laptop  50000        10       500000

Overall Inventory Value:
711000
jahnavi


In [13]:
import pandas as pd
data = {
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "Price": [50000, 500, 1200, 10000],
    "Quantity": [10, 50, 30, 15]
}
df = pd.DataFrame(data)
df["Total Value"] = df["Price"] * df["Quantity"]
print("DataFrame:")
print(df)

print("\nProduct with Highest Total Value:")
print(df[df["Total Value"] == df["Total Value"].max()])

print("\nOverall Inventory Value:")
print(df["Total Value"].sum())

print ("jahnavi")

DataFrame:
    Product  Price  Quantity  Total Value
0    Laptop  50000        10       500000
1     Mouse    500        50        25000
2  Keyboard   1200        30        36000
3   Monitor  10000        15       150000

Product with Highest Total Value:
  Product  Price  Quantity  Total Value
0  Laptop  50000        10       500000

Overall Inventory Value:
711000
jahnavi


In [9]:
!mamba install scikit-learn

mambajs 0.21.1

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas, scikit-learn
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 1.083 seconds
All requested packages already installed.


In [12]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
# Add the Class column
df["Class"] = iris.target
print("Iris DataFrame:")
print(df)
print("\nFirst Five Records:")
print(df.head())
print("\nShape of the DataFrame:")
print(df.shape)
print("\nColumn Names:")
print(df.columns)
print("\nMissing Values:")
print(df.isnull().sum())
print("\nSummary Statistics:")
print(df.describe())
print("\nSamples in Each Class:")
print(df["Class"].value_counts())
print ("jahnavi")

Iris DataFrame:
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     Class 